name: Build Docker
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build-docker-v1_8_x:
    name: Build Docker Nodeos v1.8.x
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
        with:
          ref: master
          token: ${{ github.token }}
      - name: Get CDT Debian
        uses: actions/github-script@v3
        with:
          script: |
            const cdtVersion = '1.6.';
            const releaseList = await github.request('GET /repos/{owner}/{repo}/releases', {
              owner: 'eosio',
              repo: 'eosio.cdt'
            });
            const releases = releaseList.data.map(release => {
              const deb = release.assets.find(asset => asset.name.includes('.deb'));
              console.log(release.tag_name);
              return {
                tag: release.tag_name,
                debianUrl: deb ? deb.browser_download_url : null,
              };
            }).filter(release => release.tag.startsWith(cdtVersion));;
            console.log(releases);
  
